name: Publish release
on:
  release:
    types: [released]

jobs:
  publish-release:
    name: Publish release
    uses: logikal-io/github-workflows/.github/workflows/publish-release.yml@v4
    with:
      name: mindlab
      # Note: versions must be mirrored in the test-pull-request.yml workflow
      hadoop-version: 3.3.1
      hadoop-gcs-connector-version: 2.2.11
      hadoop-aws-module-version: 3.3.1
      aws-java-sdk-version: 1.11.901
    permissions:
      contents: read
      id-token: write
    secrets: inherit
