name: Test pull request
on: pull_request

jobs:
  run-python-tests:
    name: Run Python tests
    uses: logikal-io/github-workflows/.github/workflows/run-python-tests.yml@v2.2.0-dev0
    permissions:
      contents: read
      id-token: write
    with:
      hadoop-version: 3.3.1
      hadoop-gcs-connector-version: 2.2.5
      hadoop-aws-module-version: 3.3.1
    secrets: inherit
  run-terraform-tests:
    name: Run Terraform tests
    uses: logikal-io/github-workflows/.github/workflows/run-terraform-tests.yml@v2.1.2
