name: Test pull request
on: pull_request

jobs:
  run-python-tests:
    name: Run Python tests
    uses: logikal-io/github-workflows/.github/workflows/run-python-tests.yml@v3.0.0-dev3
    permissions:
      contents: read
      id-token: write
    with:
      hadoop-version: 3.3.1
      hadoop-gcs-connector-version: 2.2.10
      hadoop-aws-module-version: 3.3.1
      aws-java-sdk-version: 1.11.901
    secrets: inherit

  run-terraform-tests:
    name: Run Terraform tests
    uses: logikal-io/github-workflows/.github/workflows/run-terraform-tests.yml@v3.0.0-dev3
